### PR TITLE
Support validation of interfaces

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Review by mbryzek — COMMENTED** [review]
Thanks Gregor! Two thoughts:

  - can you share what problem you ran into or what you are solving for?
  - conceptually this is a potentially large change as requires us to start handling interface types directly (vs. it being largely an implementation detail where we can continue to depend on only models and unions w/ interfaces really being about validation). I'm trying to think through when we actually want just the interface type itself and what that unlocks for users

**Comment by gheine** [comment]
@mbryzek essentially we need support to find interfaces via MultiService.findType/findTypes as currently this function is blind to interfaces and returns any type except interfaces, which feels broken. Do you foresee this change breaking things elsewhere?

**Comment by mbryzek** [comment]
> @mbryzek essentially we need support to find interfaces via MultiService.findType/findTypes as currently this function is blind to interfaces and returns any type except interfaces, which feels broken. Do you foresee this change breaking things elsewhere?

Understood - I guess the question is why do we care / what are we unable to do? The impact I think of this change may be that in many places where we findType we'll now have to match on the Interface type and I think do nothing - eg.

```
findType(...) match {
  case m: Model => doSomething
  case _: Interface => // intentional no-op
}
```

**Comment by mbryzek** [comment]
closing as superseded by https://github.com/apicollective/apibuilder-validation/pull/181

**Pull request closed without merging**
